### ISSUE TITLE
Orario notifica non corretto

### ISSUE THREAD

**Issue by cela96** [botfactoryit/terremotibot#17]
L'ultimo avviso che ho ricevuto aveva l'orario sbagliato, il terremoto è avvenuto alle 2:36 ma nella notifica c'è scritto 1:36
Ho ricevuto la notifica alle 2:49
![image](https://user-images.githubusercontent.com/47556910/152682513-aa08876a-ae43-4814-a8a6-5478df1abdd8.png)

**Comment by cela96** [comment]
Ho notato che anche su twitter l'orario non è corretto https://twitter.com/TerremotiBot/status/1490140575798075395

**Comment by matteocontrini** [comment]
Risolto, grazie!
